### ISSUE TITLE
Put "Then" in test case expected result

### ISSUE THREAD

**Issue by spongessuck** [quantori/GherkinSyncTool#45]
Some other tools allow the option of putting the "Then" text of a scenario in the "expected result" field in the test case. I'm using Azure DevOps and I'm not sure if this is not an option in TestRail, but it would be a feature I'd appreciate.

**Comment by andrey-brovko** [comment]
Hello, dear user @spongessuck  :)
Do you mean something like this?
![image](https://user-images.githubusercontent.com/97605929/172365472-11cd03c3-52f3-472f-bb4e-ce183c83bb91.png)

**Comment by andrey-brovko** [comment]
@spongessuck please check out version [3.12.0](https://github.com/quantori/GherkinSyncTool/releases/tag/3.12.0). 

To enable the new feature please set `SetThenStepsAsExpected` config parameter as `true`.
