### ISSUE TITLE
Feature Request:- Upload Test cases in particular TestPlan ID and Suite ID in Azure DevOps

### ISSUE THREAD

**Issue by PavanMudigondaTR** [quantori/GherkinSyncTool#50]
Hi, 

Could you please provide option to upload Test cases in particular TestPlan ID in Azure DevOps. Can I specify TestPlan ID and Suite ID I want to upload under ? Right now all test cases are created how ever they are not being visible unless I search with Test Case ID.

**Comment by andrey-brovko** [comment]
Hello, Pavan!

GherkinSyncTool intends to create test cases and then the QA engineers create test plans and suites based on them. Also, it is possible to configure and filter test cases based on the [Area parameter ](https://github.com/quantori/GherkinSyncTool#azure-devops-settings). Other fields like test names and tags are available as well.

![image](https://user-images.githubusercontent.com/97605929/184341165-5c8c847c-a4de-43bf-97b5-ba39318ffcf2.png)
![image](https://user-images.githubusercontent.com/97605929/184341191-4e7a91b7-d3e2-4165-acb8-534efbc9c78a.png)
![image](https://user-images.githubusercontent.com/97605929/184341220-88accfe4-9e1a-4293-9270-b2de9fca0dbe.png)

In case you have another workflow please let me know.

**Comment by PavanMudigondaTR** [comment]
Thanks so much. I am able to find test cases and create test plan.
