### ISSUE TITLE
Feature Request:- Handle duplicate test cases

### ISSUE THREAD

**Issue by PavanMudigondaTR** [quantori/GherkinSyncTool#51]
Could you please check if its possible to handle duplicate test cases if test case id tag is already present. Currently its creating test cases again and again !

**Comment by andrey-brovko** [comment]
If GherkinSyncToolId [parameter ](https://github.com/quantori/GherkinSyncTool#azure-devops-settings) stays the same and the test case id tag is presented in a feature file GherkinSyncTool should not create a new test case and should update an existing one.
The test case id tag looks like this:
![image](https://user-images.githubusercontent.com/97605929/184343153-bdbff607-7430-4b44-83c1-98361c8a1bfb.png)
The test case id tag should not be deleted from the file.

Could you please provide GherkinSyncTool logs for more details?

**Comment by PavanMudigondaTR** [comment]
I think made mistake somewhere. I tried as per your instructions and it worked fine. You can close my ticket

**Comment by PavanMudigondaTR** [comment]
Thanks a lot for getting back to me
